version: '3.9'
services:
  nginx:
    image: nginx:alpine
    ports:
      - '127.0.0.1:80:80'
    volumes:
      - './nginx/dev.conf:/etc/nginx/conf.d/default.conf'
      - "./www/:/var/www"

  php:
    build: ./
    volumes:
      - "./www/:/var/www"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://nginx | grep works"]
      interval: 5s
      timeout: 5s
      retries: 5
